// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/cache.dart';
import 'api/dsp.dart';
import 'api/image_processor.dart';
import 'api/library.dart';
import 'api/loudness.dart';
import 'api/lyrics.dart';
import 'api/lyrics/htmlescape.dart';
import 'api/metadata.dart';
import 'api/models.dart';
import 'api/resolver.dart';
import 'api/search.dart';
import 'api/simple.dart';
import 'api/spotify.dart';
import 'api/visualizer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
      dynamic raw);

  @protected
  RustStreamSink<SpectrumTrackMetadata>
      dco_decode_StreamSink_spectrum_track_metadata_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioProcessor dco_decode_audio_processor(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioProcessor dco_decode_box_autoadd_audio_processor(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SpectrumLyrics dco_decode_box_autoadd_spectrum_lyrics(dynamic raw);

  @protected
  SpectrumTrackMetadata dco_decode_box_autoadd_spectrum_track_metadata(
      dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<LyricsLine> dco_decode_list_lyrics_line(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SpectrumLyrics> dco_decode_list_spectrum_lyrics(dynamic raw);

  @protected
  List<SpectrumTrackMetadata> dco_decode_list_spectrum_track_metadata(
      dynamic raw);

  @protected
  List<SpotifyPlaylist> dco_decode_list_spotify_playlist(dynamic raw);

  @protected
  LyricsLine dco_decode_lyrics_line(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SpectrumLyrics? dco_decode_opt_box_autoadd_spectrum_lyrics(dynamic raw);

  @protected
  SpectrumTrackMetadata? dco_decode_opt_box_autoadd_spectrum_track_metadata(
      dynamic raw);

  @protected
  ProcessedImage dco_decode_processed_image(dynamic raw);

  @protected
  SpectrumLyrics dco_decode_spectrum_lyrics(dynamic raw);

  @protected
  SpectrumTrackMetadata dco_decode_spectrum_track_metadata(dynamic raw);

  @protected
  SpotifyPlaylist dco_decode_spotify_playlist(dynamic raw);

  @protected
  SpotifySyncResult dco_decode_spotify_sync_result(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<SpectrumTrackMetadata>
      sse_decode_StreamSink_spectrum_track_metadata_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioProcessor sse_decode_audio_processor(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioProcessor sse_decode_box_autoadd_audio_processor(
      SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SpectrumLyrics sse_decode_box_autoadd_spectrum_lyrics(
      SseDeserializer deserializer);

  @protected
  SpectrumTrackMetadata sse_decode_box_autoadd_spectrum_track_metadata(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<LyricsLine> sse_decode_list_lyrics_line(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SpectrumLyrics> sse_decode_list_spectrum_lyrics(
      SseDeserializer deserializer);

  @protected
  List<SpectrumTrackMetadata> sse_decode_list_spectrum_track_metadata(
      SseDeserializer deserializer);

  @protected
  List<SpotifyPlaylist> sse_decode_list_spotify_playlist(
      SseDeserializer deserializer);

  @protected
  LyricsLine sse_decode_lyrics_line(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SpectrumLyrics? sse_decode_opt_box_autoadd_spectrum_lyrics(
      SseDeserializer deserializer);

  @protected
  SpectrumTrackMetadata? sse_decode_opt_box_autoadd_spectrum_track_metadata(
      SseDeserializer deserializer);

  @protected
  ProcessedImage sse_decode_processed_image(SseDeserializer deserializer);

  @protected
  SpectrumLyrics sse_decode_spectrum_lyrics(SseDeserializer deserializer);

  @protected
  SpectrumTrackMetadata sse_decode_spectrum_track_metadata(
      SseDeserializer deserializer);

  @protected
  SpotifyPlaylist sse_decode_spotify_playlist(SseDeserializer deserializer);

  @protected
  SpotifySyncResult sse_decode_spotify_sync_result(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
      RustStreamSink<Float32List> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_spectrum_track_metadata_Sse(
      RustStreamSink<SpectrumTrackMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_processor(
      AudioProcessor self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audio_processor(
      AudioProcessor self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spectrum_lyrics(
      SpectrumLyrics self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_spectrum_track_metadata(
      SpectrumTrackMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lyrics_line(
      List<LyricsLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_loose(
      List<double> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_spectrum_lyrics(
      List<SpectrumLyrics> self, SseSerializer serializer);

  @protected
  void sse_encode_list_spectrum_track_metadata(
      List<SpectrumTrackMetadata> self, SseSerializer serializer);

  @protected
  void sse_encode_list_spotify_playlist(
      List<SpotifyPlaylist> self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_line(LyricsLine self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_spectrum_lyrics(
      SpectrumLyrics? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_spectrum_track_metadata(
      SpectrumTrackMetadata? self, SseSerializer serializer);

  @protected
  void sse_encode_processed_image(
      ProcessedImage self, SseSerializer serializer);

  @protected
  void sse_encode_spectrum_lyrics(
      SpectrumLyrics self, SseSerializer serializer);

  @protected
  void sse_encode_spectrum_track_metadata(
      SpectrumTrackMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_spotify_playlist(
      SpotifyPlaylist self, SseSerializer serializer);

  @protected
  void sse_encode_spotify_sync_result(
      SpotifySyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
