// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/dsp.dart';
import 'api/image_processor.dart';
import 'api/library.dart';
import 'api/loudness.dart';
import 'api/lyrics.dart';
import 'api/lyrics/htmlescape.dart';
import 'api/metadata.dart';
import 'api/models.dart';
import 'api/resolver.dart';
import 'api/search.dart';
import 'api/simple.dart';
import 'api/spotify.dart';
import 'api/visualizer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 1513806511;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_spectrum',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiDspAudioProcessorGenerateMpvAfString(
      {required AudioProcessor that});

  Future<double> crateApiLoudnessCalculateReplayGain({required String path});

  Future<bool> crateApiCacheCheckCacheExists({required String path});

  Future<void> crateApiCacheClearOldCache(
      {required String directory, required BigInt maxSizeBytes});

  Future<String?> crateApiLyricsHtmlescapeDecodeHtml({required String s});

  Future<void> crateApiCacheDownloadTo(
      {required String url, required String path});

  Future<ProcessedImage> crateApiImageProcessorExtractAndProcessCover(
      {required String audioPath, required String cacheDir});

  Future<SpectrumTrackMetadata?> crateApiResolverFindBestMatch(
      {required SpectrumTrackMetadata original, required String source});

  Future<List<List<String>>> crateApiLibraryFindDuplicates(
      {required List<SpectrumTrackMetadata> tracks});

  Future<List<SpectrumLyrics>> crateApiLyricsGetAllLyrics(
      {required String title,
      required String artist,
      String? album,
      required PlatformInt64 durationMs});

  Future<SpectrumLyrics?> crateApiLyricsGetLyrics(
      {required String title,
      required String artist,
      String? album,
      required PlatformInt64 durationMs});

  Future<String> crateApiDspGetRestorationPreset();

  Future<void> crateApiSimpleInitApp();

  Future<SpectrumTrackMetadata> crateApiMetadataNormalizeMetadata(
      {required SpectrumTrackMetadata track});

  Future<List<SpectrumTrackMetadata>> crateApiMetadataNormalizeMetadataBulk(
      {required List<SpectrumTrackMetadata> tracks});

  Future<Float32List> crateApiVisualizerProcessFftData(
      {required List<double> raw});

  Future<ProcessedImage> crateApiImageProcessorProcessImage(
      {required String inputPath, required String cacheDir});

  Future<String?> crateApiSimpleResolveSoundcloudStream(
      {required String query, PlatformInt64? expectedDurationMs});

  Future<String?> crateApiSimpleResolveYoutubeStream({required String videoId});

  Stream<SpectrumTrackMetadata> crateApiLibraryScanLocalDirectory(
      {required String path, required String cacheDir});

  Future<double> crateApiMetadataScoreMatch(
      {required SpectrumTrackMetadata original,
      required SpectrumTrackMetadata candidate});

  Future<List<SpectrumTrackMetadata>> crateApiLibrarySearchInTracks(
      {required String query, required List<SpectrumTrackMetadata> tracks});

  Future<List<SpectrumTrackMetadata>> crateApiSimpleSearchTracks(
      {required String query, required String source});

  Stream<Float32List> crateApiVisualizerStartFftStream();

  Future<SpotifySyncResult> crateApiSpotifySyncSpotifyLibrary(
      {required String token});

  Future<List<SpectrumTrackMetadata>> crateApiSearchUnifiedSearch(
      {required String query,
      required List<SpectrumTrackMetadata> localTracks,
      required String source});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiDspAudioProcessorGenerateMpvAfString(
      {required AudioProcessor that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_audio_processor(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDspAudioProcessorGenerateMpvAfStringConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDspAudioProcessorGenerateMpvAfStringConstMeta =>
      const TaskConstMeta(
        debugName: 'audio_processor_generate_mpv_af_string',
        argNames: ['that'],
      );

  @override
  Future<double> crateApiLoudnessCalculateReplayGain({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLoudnessCalculateReplayGainConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLoudnessCalculateReplayGainConstMeta =>
      const TaskConstMeta(
        debugName: 'calculate_replay_gain',
        argNames: ['path'],
      );

  @override
  Future<bool> crateApiCacheCheckCacheExists({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCacheCheckCacheExistsConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheCheckCacheExistsConstMeta =>
      const TaskConstMeta(
        debugName: 'check_cache_exists',
        argNames: ['path'],
      );

  @override
  Future<void> crateApiCacheClearOldCache(
      {required String directory, required BigInt maxSizeBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(directory, serializer);
        sse_encode_u_64(maxSizeBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCacheClearOldCacheConstMeta,
      argValues: [directory, maxSizeBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheClearOldCacheConstMeta => const TaskConstMeta(
        debugName: 'clear_old_cache',
        argNames: ['directory', 'maxSizeBytes'],
      );

  @override
  Future<String?> crateApiLyricsHtmlescapeDecodeHtml({required String s}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(s, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLyricsHtmlescapeDecodeHtmlConstMeta,
      argValues: [s],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLyricsHtmlescapeDecodeHtmlConstMeta =>
      const TaskConstMeta(
        debugName: 'decode_html',
        argNames: ['s'],
      );

  @override
  Future<void> crateApiCacheDownloadTo(
      {required String url, required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCacheDownloadToConstMeta,
      argValues: [url, path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCacheDownloadToConstMeta => const TaskConstMeta(
        debugName: 'download_to',
        argNames: ['url', 'path'],
      );

  @override
  Future<ProcessedImage> crateApiImageProcessorExtractAndProcessCover(
      {required String audioPath, required String cacheDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(audioPath, serializer);
        sse_encode_String(cacheDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_processed_image,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiImageProcessorExtractAndProcessCoverConstMeta,
      argValues: [audioPath, cacheDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImageProcessorExtractAndProcessCoverConstMeta =>
      const TaskConstMeta(
        debugName: 'extract_and_process_cover',
        argNames: ['audioPath', 'cacheDir'],
      );

  @override
  Future<SpectrumTrackMetadata?> crateApiResolverFindBestMatch(
      {required SpectrumTrackMetadata original, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_spectrum_track_metadata(original, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiResolverFindBestMatchConstMeta,
      argValues: [original, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResolverFindBestMatchConstMeta =>
      const TaskConstMeta(
        debugName: 'find_best_match',
        argNames: ['original', 'source'],
      );

  @override
  Future<List<List<String>>> crateApiLibraryFindDuplicates(
      {required List<SpectrumTrackMetadata> tracks}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_spectrum_track_metadata(tracks, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibraryFindDuplicatesConstMeta,
      argValues: [tracks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibraryFindDuplicatesConstMeta =>
      const TaskConstMeta(
        debugName: 'find_duplicates',
        argNames: ['tracks'],
      );

  @override
  Future<List<SpectrumLyrics>> crateApiLyricsGetAllLyrics(
      {required String title,
      required String artist,
      String? album,
      required PlatformInt64 durationMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(title, serializer);
        sse_encode_String(artist, serializer);
        sse_encode_opt_String(album, serializer);
        sse_encode_i_64(durationMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_spectrum_lyrics,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLyricsGetAllLyricsConstMeta,
      argValues: [title, artist, album, durationMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLyricsGetAllLyricsConstMeta => const TaskConstMeta(
        debugName: 'get_all_lyrics',
        argNames: ['title', 'artist', 'album', 'durationMs'],
      );

  @override
  Future<SpectrumLyrics?> crateApiLyricsGetLyrics(
      {required String title,
      required String artist,
      String? album,
      required PlatformInt64 durationMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(title, serializer);
        sse_encode_String(artist, serializer);
        sse_encode_opt_String(album, serializer);
        sse_encode_i_64(durationMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_box_autoadd_spectrum_lyrics,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLyricsGetLyricsConstMeta,
      argValues: [title, artist, album, durationMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLyricsGetLyricsConstMeta => const TaskConstMeta(
        debugName: 'get_lyrics',
        argNames: ['title', 'artist', 'album', 'durationMs'],
      );

  @override
  Future<String> crateApiDspGetRestorationPreset() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDspGetRestorationPresetConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDspGetRestorationPresetConstMeta =>
      const TaskConstMeta(
        debugName: 'get_restoration_preset',
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: 'init_app',
        argNames: [],
      );

  @override
  Future<SpectrumTrackMetadata> crateApiMetadataNormalizeMetadata(
      {required SpectrumTrackMetadata track}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_spectrum_track_metadata(track, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataNormalizeMetadataConstMeta,
      argValues: [track],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataNormalizeMetadataConstMeta =>
      const TaskConstMeta(
        debugName: 'normalize_metadata',
        argNames: ['track'],
      );

  @override
  Future<List<SpectrumTrackMetadata>> crateApiMetadataNormalizeMetadataBulk(
      {required List<SpectrumTrackMetadata> tracks}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_spectrum_track_metadata(tracks, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataNormalizeMetadataBulkConstMeta,
      argValues: [tracks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataNormalizeMetadataBulkConstMeta =>
      const TaskConstMeta(
        debugName: 'normalize_metadata_bulk',
        argNames: ['tracks'],
      );

  @override
  Future<Float32List> crateApiVisualizerProcessFftData(
      {required List<double> raw}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_f_32_loose(raw, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_f_32_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVisualizerProcessFftDataConstMeta,
      argValues: [raw],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVisualizerProcessFftDataConstMeta =>
      const TaskConstMeta(
        debugName: 'process_fft_data',
        argNames: ['raw'],
      );

  @override
  Future<ProcessedImage> crateApiImageProcessorProcessImage(
      {required String inputPath, required String cacheDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(inputPath, serializer);
        sse_encode_String(cacheDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_processed_image,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiImageProcessorProcessImageConstMeta,
      argValues: [inputPath, cacheDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiImageProcessorProcessImageConstMeta =>
      const TaskConstMeta(
        debugName: 'process_image',
        argNames: ['inputPath', 'cacheDir'],
      );

  @override
  Future<String?> crateApiSimpleResolveSoundcloudStream(
      {required String query, PlatformInt64? expectedDurationMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_opt_box_autoadd_i_64(expectedDurationMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleResolveSoundcloudStreamConstMeta,
      argValues: [query, expectedDurationMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleResolveSoundcloudStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'resolve_soundcloud_stream',
        argNames: ['query', 'expectedDurationMs'],
      );

  @override
  Future<String?> crateApiSimpleResolveYoutubeStream(
      {required String videoId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(videoId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleResolveYoutubeStreamConstMeta,
      argValues: [videoId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleResolveYoutubeStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'resolve_youtube_stream',
        argNames: ['videoId'],
      );

  @override
  Stream<SpectrumTrackMetadata> crateApiLibraryScanLocalDirectory(
      {required String path, required String cacheDir}) {
    final sink = RustStreamSink<SpectrumTrackMetadata>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(cacheDir, serializer);
        sse_encode_StreamSink_spectrum_track_metadata_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiLibraryScanLocalDirectoryConstMeta,
      argValues: [path, cacheDir, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLibraryScanLocalDirectoryConstMeta =>
      const TaskConstMeta(
        debugName: 'scan_local_directory',
        argNames: ['path', 'cacheDir', 'sink'],
      );

  @override
  Future<double> crateApiMetadataScoreMatch(
      {required SpectrumTrackMetadata original,
      required SpectrumTrackMetadata candidate}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_spectrum_track_metadata(original, serializer);
        sse_encode_box_autoadd_spectrum_track_metadata(candidate, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMetadataScoreMatchConstMeta,
      argValues: [original, candidate],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMetadataScoreMatchConstMeta => const TaskConstMeta(
        debugName: 'score_match',
        argNames: ['original', 'candidate'],
      );

  @override
  Future<List<SpectrumTrackMetadata>> crateApiLibrarySearchInTracks(
      {required String query, required List<SpectrumTrackMetadata> tracks}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_list_spectrum_track_metadata(tracks, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLibrarySearchInTracksConstMeta,
      argValues: [query, tracks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLibrarySearchInTracksConstMeta =>
      const TaskConstMeta(
        debugName: 'search_in_tracks',
        argNames: ['query', 'tracks'],
      );

  @override
  Future<List<SpectrumTrackMetadata>> crateApiSimpleSearchTracks(
      {required String query, required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleSearchTracksConstMeta,
      argValues: [query, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSearchTracksConstMeta => const TaskConstMeta(
        debugName: 'search_tracks',
        argNames: ['query', 'source'],
      );

  @override
  Stream<Float32List> crateApiVisualizerStartFftStream() {
    final sink = RustStreamSink<Float32List>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_list_prim_f_32_strict_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiVisualizerStartFftStreamConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiVisualizerStartFftStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'start_fft_stream',
        argNames: ['sink'],
      );

  @override
  Future<SpotifySyncResult> crateApiSpotifySyncSpotifyLibrary(
      {required String token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_spotify_sync_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSpotifySyncSpotifyLibraryConstMeta,
      argValues: [token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSpotifySyncSpotifyLibraryConstMeta =>
      const TaskConstMeta(
        debugName: 'sync_spotify_library',
        argNames: ['token'],
      );

  @override
  Future<List<SpectrumTrackMetadata>> crateApiSearchUnifiedSearch(
      {required String query,
      required List<SpectrumTrackMetadata> localTracks,
      required String source}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(query, serializer);
        sse_encode_list_spectrum_track_metadata(localTracks, serializer);
        sse_encode_String(source, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_spectrum_track_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSearchUnifiedSearchConstMeta,
      argValues: [query, localTracks, source],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSearchUnifiedSearchConstMeta =>
      const TaskConstMeta(
        debugName: 'unified_search',
        argNames: ['query', 'localTracks', 'source'],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Float32List> dco_decode_StreamSink_list_prim_f_32_strict_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SpectrumTrackMetadata>
      dco_decode_StreamSink_spectrum_track_metadata_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioProcessor dco_decode_audio_processor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AudioProcessor(
      restorationEnabled: dco_decode_bool(arr[0]),
      volumeDb: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AudioProcessor dco_decode_box_autoadd_audio_processor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_audio_processor(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  SpectrumLyrics dco_decode_box_autoadd_spectrum_lyrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_spectrum_lyrics(raw);
  }

  @protected
  SpectrumTrackMetadata dco_decode_box_autoadd_spectrum_track_metadata(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_spectrum_track_metadata(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<LyricsLine> dco_decode_list_lyrics_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyrics_line).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SpectrumLyrics> dco_decode_list_spectrum_lyrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_spectrum_lyrics).toList();
  }

  @protected
  List<SpectrumTrackMetadata> dco_decode_list_spectrum_track_metadata(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_spectrum_track_metadata)
        .toList();
  }

  @protected
  List<SpotifyPlaylist> dco_decode_list_spotify_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_spotify_playlist).toList();
  }

  @protected
  LyricsLine dco_decode_lyrics_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LyricsLine(
      timeMs: dco_decode_i_64(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SpectrumLyrics? dco_decode_opt_box_autoadd_spectrum_lyrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_spectrum_lyrics(raw);
  }

  @protected
  SpectrumTrackMetadata? dco_decode_opt_box_autoadd_spectrum_track_metadata(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_spectrum_track_metadata(raw);
  }

  @protected
  ProcessedImage dco_decode_processed_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProcessedImage(
      dominantColorHex: dco_decode_String(arr[0]),
      thumbnailPath: dco_decode_String(arr[1]),
      blurHashSubset: dco_decode_String(arr[2]),
    );
  }

  @protected
  SpectrumLyrics dco_decode_spectrum_lyrics(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SpectrumLyrics(
      content: dco_decode_String(arr[0]),
      lines: dco_decode_list_lyrics_line(arr[1]),
      source: dco_decode_String(arr[2]),
    );
  }

  @protected
  SpectrumTrackMetadata dco_decode_spectrum_track_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return SpectrumTrackMetadata(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artist: dco_decode_String(arr[2]),
      durationMs: dco_decode_i_64(arr[3]),
      artworkUrl: dco_decode_opt_String(arr[4]),
      source: dco_decode_String(arr[5]),
      localPath: dco_decode_opt_String(arr[6]),
      dominantColor: dco_decode_opt_String(arr[7]),
      blurHashPath: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  SpotifyPlaylist dco_decode_spotify_playlist(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SpotifyPlaylist(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      artworkUrl: dco_decode_opt_String(arr[2]),
      trackIds: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  SpotifySyncResult dco_decode_spotify_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SpotifySyncResult(
      tracks: dco_decode_list_spectrum_track_metadata(arr[0]),
      playlists: dco_decode_list_spotify_playlist(arr[1]),
      likedTrackIds: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Float32List> sse_decode_StreamSink_list_prim_f_32_strict_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SpectrumTrackMetadata>
      sse_decode_StreamSink_spectrum_track_metadata_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioProcessor sse_decode_audio_processor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_restorationEnabled = sse_decode_bool(deserializer);
    var var_volumeDb = sse_decode_f_64(deserializer);
    return AudioProcessor(
        restorationEnabled: var_restorationEnabled, volumeDb: var_volumeDb);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AudioProcessor sse_decode_box_autoadd_audio_processor(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_audio_processor(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  SpectrumLyrics sse_decode_box_autoadd_spectrum_lyrics(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_spectrum_lyrics(deserializer));
  }

  @protected
  SpectrumTrackMetadata sse_decode_box_autoadd_spectrum_track_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_spectrum_track_metadata(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LyricsLine> sse_decode_list_lyrics_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricsLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyrics_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SpectrumLyrics> sse_decode_list_spectrum_lyrics(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpectrumLyrics>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_spectrum_lyrics(deserializer));
    }
    return ans_;
  }

  @protected
  List<SpectrumTrackMetadata> sse_decode_list_spectrum_track_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpectrumTrackMetadata>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_spectrum_track_metadata(deserializer));
    }
    return ans_;
  }

  @protected
  List<SpotifyPlaylist> sse_decode_list_spotify_playlist(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpotifyPlaylist>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_spotify_playlist(deserializer));
    }
    return ans_;
  }

  @protected
  LyricsLine sse_decode_lyrics_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timeMs = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return LyricsLine(timeMs: var_timeMs, text: var_text);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SpectrumLyrics? sse_decode_opt_box_autoadd_spectrum_lyrics(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_spectrum_lyrics(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SpectrumTrackMetadata? sse_decode_opt_box_autoadd_spectrum_track_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_spectrum_track_metadata(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProcessedImage sse_decode_processed_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dominantColorHex = sse_decode_String(deserializer);
    var var_thumbnailPath = sse_decode_String(deserializer);
    var var_blurHashSubset = sse_decode_String(deserializer);
    return ProcessedImage(
        dominantColorHex: var_dominantColorHex,
        thumbnailPath: var_thumbnailPath,
        blurHashSubset: var_blurHashSubset);
  }

  @protected
  SpectrumLyrics sse_decode_spectrum_lyrics(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_String(deserializer);
    var var_lines = sse_decode_list_lyrics_line(deserializer);
    var var_source = sse_decode_String(deserializer);
    return SpectrumLyrics(
        content: var_content, lines: var_lines, source: var_source);
  }

  @protected
  SpectrumTrackMetadata sse_decode_spectrum_track_metadata(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artist = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_localPath = sse_decode_opt_String(deserializer);
    var var_dominantColor = sse_decode_opt_String(deserializer);
    var var_blurHashPath = sse_decode_opt_String(deserializer);
    return SpectrumTrackMetadata(
        id: var_id,
        title: var_title,
        artist: var_artist,
        durationMs: var_durationMs,
        artworkUrl: var_artworkUrl,
        source: var_source,
        localPath: var_localPath,
        dominantColor: var_dominantColor,
        blurHashPath: var_blurHashPath);
  }

  @protected
  SpotifyPlaylist sse_decode_spotify_playlist(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_artworkUrl = sse_decode_opt_String(deserializer);
    var var_trackIds = sse_decode_list_String(deserializer);
    return SpotifyPlaylist(
        id: var_id,
        name: var_name,
        artworkUrl: var_artworkUrl,
        trackIds: var_trackIds);
  }

  @protected
  SpotifySyncResult sse_decode_spotify_sync_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tracks = sse_decode_list_spectrum_track_metadata(deserializer);
    var var_playlists = sse_decode_list_spotify_playlist(deserializer);
    var var_likedTrackIds = sse_decode_list_String(deserializer);
    return SpotifySyncResult(
        tracks: var_tracks,
        playlists: var_playlists,
        likedTrackIds: var_likedTrackIds);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_f_32_strict_Sse(
      RustStreamSink<Float32List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_spectrum_track_metadata_Sse(
      RustStreamSink<SpectrumTrackMetadata> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_spectrum_track_metadata,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_processor(
      AudioProcessor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.restorationEnabled, serializer);
    sse_encode_f_64(self.volumeDb, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_audio_processor(
      AudioProcessor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_audio_processor(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_spectrum_lyrics(
      SpectrumLyrics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_spectrum_lyrics(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_spectrum_track_metadata(
      SpectrumTrackMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_spectrum_track_metadata(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lyrics_line(
      List<LyricsLine> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyrics_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
      List<double> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
        self is Float32List ? self : Float32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_spectrum_lyrics(
      List<SpectrumLyrics> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_spectrum_lyrics(item, serializer);
    }
  }

  @protected
  void sse_encode_list_spectrum_track_metadata(
      List<SpectrumTrackMetadata> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_spectrum_track_metadata(item, serializer);
    }
  }

  @protected
  void sse_encode_list_spotify_playlist(
      List<SpotifyPlaylist> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_spotify_playlist(item, serializer);
    }
  }

  @protected
  void sse_encode_lyrics_line(LyricsLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timeMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_spectrum_lyrics(
      SpectrumLyrics? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_spectrum_lyrics(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_spectrum_track_metadata(
      SpectrumTrackMetadata? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_spectrum_track_metadata(self, serializer);
    }
  }

  @protected
  void sse_encode_processed_image(
      ProcessedImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dominantColorHex, serializer);
    sse_encode_String(self.thumbnailPath, serializer);
    sse_encode_String(self.blurHashSubset, serializer);
  }

  @protected
  void sse_encode_spectrum_lyrics(
      SpectrumLyrics self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.content, serializer);
    sse_encode_list_lyrics_line(self.lines, serializer);
    sse_encode_String(self.source, serializer);
  }

  @protected
  void sse_encode_spectrum_track_metadata(
      SpectrumTrackMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artist, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_opt_String(self.localPath, serializer);
    sse_encode_opt_String(self.dominantColor, serializer);
    sse_encode_opt_String(self.blurHashPath, serializer);
  }

  @protected
  void sse_encode_spotify_playlist(
      SpotifyPlaylist self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.artworkUrl, serializer);
    sse_encode_list_String(self.trackIds, serializer);
  }

  @protected
  void sse_encode_spotify_sync_result(
      SpotifySyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_spectrum_track_metadata(self.tracks, serializer);
    sse_encode_list_spotify_playlist(self.playlists, serializer);
    sse_encode_list_String(self.likedTrackIds, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
