platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = '1'

# Умный поиск podhelper.rb
podhelper_path = File.expand_path(File.join('Flutter', 'podhelper.rb'), __dir__)
if !File.exist?(podhelper_path)
  # Если в проекте нет, берем напрямую из установленного Flutter SDK
  flutter_root = ENV['FLUTTER_ROOT']
  if flutter_root
    podhelper_path = File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')
  end
end

if File.exist?(podhelper_path)
  require podhelper_path
else
  raise "podhelper.rb not found in project or FLUTTER_ROOT. Check your Flutter installation."
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = 'arm64'
      
      # Исправления для совместимости
      config.build_settings['CLANG_ENABLE_MODULE_DEBUGGING'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
      config.build_settings['COMPILER_INDEX_STORE_ENABLE'] = 'NO'
    end
  end
end
