// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `DownloadProgress`

Future<void> downloadTo({required String url, required String path}) =>
    RustLib.instance.api.crateApiCacheDownloadTo(url: url, path: path);

Future<bool> checkCacheExists({required String path}) =>
    RustLib.instance.api.crateApiCacheCheckCacheExists(path: path);

Future<void> clearOldCache(
        {required String directory, required BigInt maxSizeBytes}) =>
    RustLib.instance.api.crateApiCacheClearOldCache(
        directory: directory, maxSizeBytes: maxSizeBytes);
