// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> getRestorationPreset() =>
    RustLib.instance.api.crateApiDspGetRestorationPreset();

class AudioProcessor {
  final bool restorationEnabled;
  final double volumeDb;

  const AudioProcessor({
    required this.restorationEnabled,
    required this.volumeDb,
  });

  Future<String> generateMpvAfString() =>
      RustLib.instance.api.crateApiDspAudioProcessorGenerateMpvAfString(
        that: this,
      );

  @override
  int get hashCode => restorationEnabled.hashCode ^ volumeDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioProcessor &&
          runtimeType == other.runtimeType &&
          restorationEnabled == other.restorationEnabled &&
          volumeDb == other.volumeDb;
}
