// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `process_dynamic_image`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<ProcessedImage> processImage(
        {required String inputPath, required String cacheDir}) =>
    RustLib.instance.api.crateApiImageProcessorProcessImage(
        inputPath: inputPath, cacheDir: cacheDir);

Future<ProcessedImage> extractAndProcessCover(
        {required String audioPath, required String cacheDir}) =>
    RustLib.instance.api.crateApiImageProcessorExtractAndProcessCover(
        audioPath: audioPath, cacheDir: cacheDir);

class ProcessedImage {
  final String dominantColorHex;
  final String thumbnailPath;
  final String blurHashSubset;

  const ProcessedImage({
    required this.dominantColorHex,
    required this.thumbnailPath,
    required this.blurHashSubset,
  });

  @override
  int get hashCode =>
      dominantColorHex.hashCode ^
      thumbnailPath.hashCode ^
      blurHashSubset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedImage &&
          runtimeType == other.runtimeType &&
          dominantColorHex == other.dominantColorHex &&
          thumbnailPath == other.thumbnailPath &&
          blurHashSubset == other.blurHashSubset;
}
