// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<SpectrumTrackMetadata>> searchInTracks(
        {required String query, required List<SpectrumTrackMetadata> tracks}) =>
    RustLib.instance.api
        .crateApiLibrarySearchInTracks(query: query, tracks: tracks);

Future<List<List<String>>> findDuplicates(
        {required List<SpectrumTrackMetadata> tracks}) =>
    RustLib.instance.api.crateApiLibraryFindDuplicates(tracks: tracks);

Stream<SpectrumTrackMetadata> scanLocalDirectory(
        {required String path, required String cacheDir}) =>
    RustLib.instance.api
        .crateApiLibraryScanLocalDirectory(path: path, cacheDir: cacheDir);
