// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_query`, `fetch_genius`, `fetch_lrclib_search`, `fetch_lrclib`, `fetch_lyrics_ovh`, `fetch_netease`, `has_lrc_timestamps`, `parse_lrc`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<SpectrumLyrics?> getLyrics(
        {required String title,
        required String artist,
        String? album,
        required PlatformInt64 durationMs}) =>
    RustLib.instance.api.crateApiLyricsGetLyrics(
        title: title, artist: artist, album: album, durationMs: durationMs);

Future<List<SpectrumLyrics>> getAllLyrics(
        {required String title,
        required String artist,
        String? album,
        required PlatformInt64 durationMs}) =>
    RustLib.instance.api.crateApiLyricsGetAllLyrics(
        title: title, artist: artist, album: album, durationMs: durationMs);

class LyricsLine {
  final PlatformInt64 timeMs;
  final String text;

  const LyricsLine({
    required this.timeMs,
    required this.text,
  });

  @override
  int get hashCode => timeMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsLine &&
          runtimeType == other.runtimeType &&
          timeMs == other.timeMs &&
          text == other.text;
}

class SpectrumLyrics {
  final String content;
  final List<LyricsLine> lines;
  final String source;

  const SpectrumLyrics({
    required this.content,
    required this.lines,
    required this.source,
  });

  @override
  int get hashCode => content.hashCode ^ lines.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpectrumLyrics &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          lines == other.lines &&
          source == other.source;
}
