// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `ResolvedMapping`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<double> scoreMatch(
        {required SpectrumTrackMetadata original,
        required SpectrumTrackMetadata candidate}) =>
    RustLib.instance.api
        .crateApiMetadataScoreMatch(original: original, candidate: candidate);

Future<SpectrumTrackMetadata> normalizeMetadata(
        {required SpectrumTrackMetadata track}) =>
    RustLib.instance.api.crateApiMetadataNormalizeMetadata(track: track);

Future<List<SpectrumTrackMetadata>> normalizeMetadataBulk(
        {required List<SpectrumTrackMetadata> tracks}) =>
    RustLib.instance.api.crateApiMetadataNormalizeMetadataBulk(tracks: tracks);
