// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class SpectrumTrackMetadata {
  final String id;
  final String title;
  final String artist;
  final PlatformInt64 durationMs;
  final String? artworkUrl;
  final String source;
  final String? localPath;
  final String? dominantColor;
  final String? blurHashPath;

  const SpectrumTrackMetadata({
    required this.id,
    required this.title,
    required this.artist,
    required this.durationMs,
    this.artworkUrl,
    required this.source,
    this.localPath,
    this.dominantColor,
    this.blurHashPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      durationMs.hashCode ^
      artworkUrl.hashCode ^
      source.hashCode ^
      localPath.hashCode ^
      dominantColor.hashCode ^
      blurHashPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpectrumTrackMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          durationMs == other.durationMs &&
          artworkUrl == other.artworkUrl &&
          source == other.source &&
          localPath == other.localPath &&
          dominantColor == other.dominantColor &&
          blurHashPath == other.blurHashPath;
}
