// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_relevance_score`

/// The Matrix Search Engine.
/// Unifies local library, YouTube, and SoundCloud into a single ranked stream.
Future<List<SpectrumTrackMetadata>> unifiedSearch(
        {required String query,
        required List<SpectrumTrackMetadata> localTracks,
        required String source}) =>
    RustLib.instance.api.crateApiSearchUnifiedSearch(
        query: query, localTracks: localTracks, source: source);
