// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_sc_client_id`, `score_youtube_match`

Future<String?> resolveYoutubeStream({required String videoId}) =>
    RustLib.instance.api.crateApiSimpleResolveYoutubeStream(videoId: videoId);

Future<String?> resolveSoundcloudStream(
        {required String query, PlatformInt64? expectedDurationMs}) =>
    RustLib.instance.api.crateApiSimpleResolveSoundcloudStream(
        query: query, expectedDurationMs: expectedDurationMs);

Future<List<SpectrumTrackMetadata>> searchTracks(
        {required String query, required String source}) =>
    RustLib.instance.api
        .crateApiSimpleSearchTracks(query: query, source: source);
