// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_spotify_track`
// These types are ignored because they are not used by any `pub` functions: `SpotifyPlaylistResponse`, `SpotifyTrackResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<SpotifySyncResult> syncSpotifyLibrary({required String token}) =>
    RustLib.instance.api.crateApiSpotifySyncSpotifyLibrary(token: token);

class SpotifyPlaylist {
  final String id;
  final String name;
  final String? artworkUrl;
  final List<String> trackIds;

  const SpotifyPlaylist({
    required this.id,
    required this.name,
    this.artworkUrl,
    required this.trackIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ artworkUrl.hashCode ^ trackIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotifyPlaylist &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          artworkUrl == other.artworkUrl &&
          trackIds == other.trackIds;
}

class SpotifySyncResult {
  final List<SpectrumTrackMetadata> tracks;
  final List<SpotifyPlaylist> playlists;
  final List<String> likedTrackIds;

  const SpotifySyncResult({
    required this.tracks,
    required this.playlists,
    required this.likedTrackIds,
  });

  @override
  int get hashCode =>
      tracks.hashCode ^ playlists.hashCode ^ likedTrackIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotifySyncResult &&
          runtimeType == other.runtimeType &&
          tracks == other.tracks &&
          playlists == other.playlists &&
          likedTrackIds == other.likedTrackIds;
}
