// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_process_fft_data_internal`, `find_bluetooth_monitor`, `hard_patch_isolation`, `log_audit`, `name_match`

Future<Float32List> processFftData({required List<double> raw}) =>
    RustLib.instance.api.crateApiVisualizerProcessFftData(raw: raw);

Stream<Float32List> startFftStream() =>
    RustLib.instance.api.crateApiVisualizerStartFftStream();
